const fs = require("fs");
const path = require("path");

const chainsDir = path.join(__dirname, "../../data/chains");

console.log("Generating chains index...");

const files = fs.readdirSync(chainsDir);
const autogeneratedComment = `// This file is auto-generated on pre-commit to avoid maintaining it.\n// Do not modify manually as it will be overwritten.\n// Last generation on ${new Date().toLocaleString()}.\n`;
const exportStatements = files
  .filter((file) => file !== "index.ts")
  .map((file) => `export * from './${file.slice(0, -3)}';`);
const indexContent = [autogeneratedComment, ...exportStatements].join("\n");
fs.writeFileSync(path.join(chainsDir, "index.ts"), indexContent);

console.log("✅ Generating chains index");
