const fs = require('fs');
const path = require('path');

const chainsDir = path.join(__dirname, '../../data/chains');

console.log('Generating chains index...');

const files = fs.readdirSync(chainsDir);
const autogeneratedComment = `// This file is auto-generated on pre-commit to avoid maintaining it.\n// Do not modify manually as it will be overwritten.\n// Last generation on ${new Date().toLocaleString()}.\n`;
const importStatements = files
  .filter((file) => file !== 'index.ts')
  .map((file) => `import ${file.slice(0, -3)} from './${file.slice(0, -3)}';`);
const defaultExport = `export default { ${files
  .filter((file) => file !== 'index.ts')
  .map((file) => file.slice(0, -3))
  .join(', ')} };`;
const indexContent = [
  autogeneratedComment,
  ...importStatements,
  defaultExport,
].join('\n');
fs.writeFileSync(path.join(chainsDir, 'index.ts'), indexContent);

console.log('✅ Generating chains index');
