// This file is auto-generated on pre-commit to avoid maintaining it / circular dependencies.
// Do not modify manually as it will be overwritten.
// Last generation on 2024-03-04, 7:46:12 p.m..
export type PinaxId =
  | 'alfajores'
  | 'arbgoerli'
  | 'arbone'
  | 'arbsepolia'
  | 'arweave'
  | 'avalanche'
  | 'base'
  | 'bitcoin'
  | 'bsc'
  | 'celo'
  | 'chapel'
  | 'chiado'
  | 'cosmoshub'
  | 'decimal'
  | 'eos'
  | 'eth'
  | 'fantom'
  | 'gnosis'
  | 'goerli'
  | 'holesky'
  | 'jungle4'
  | 'kava'
  | 'kylin'
  | 'moonbeam'
  | 'mumbai'
  | 'near'
  | 'neartest'
  | 'optimism'
  | 'osmosis'
  | 'polygon'
  | 'scroll'
  | 'sepolia'
  | 'starknet'
  | 'telos'
  | 'telostest'
  | 'theta'
  | 'wax'
  | 'waxtest'
  | 'zkatana';
